[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI
  tzapu/WiFiManager
  https://github.com/me-no-dev/AsyncTCP.git
  https://github.com/me-no-dev/ESPAsyncWebServer.git
  bblanchon/ArduinoJson
upload_speed = 921600
board_build.filesystem = littlefs
build_flags =
  ; TFT_eSPI — USER_SETUP_LOADED means ALL config comes from these flags
  -DUSER_SETUP_LOADED
  -DILI9488_DRIVER
  -DTFT_MISO=19
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_CS=5
  -DTFT_DC=16
  -DTFT_RST=17
  -DTFT_WIDTH=320
  -DTFT_HEIGHT=480
  -DSPI_FREQUENCY=27000000
  -DSPI_READ_FREQUENCY=5000000
  -DLOAD_GLCD
  -DLOAD_FONT2
  -DLOAD_FONT4
  -DSMOOTH_FONT
